# Generated by Django 4.0.4 on 2022-05-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='./static/myapp/images/django.png', upload_to='media/'),
        ),
    ]
