# Generated by Django 4.0.4 on 2022-05-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.IntegerField(unique=True),
        ),
    ]
